name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: sudo apt-get update; sudo apt-get install build-essential libgl1-mesa-dev
      
    - name: Build
      run: ls -l; cd src; mkdir build; cd build; cmake ..; make
#       ls -l
#       cd src
#       mkdir build
#       cd build
#       cmake ..
#       make


#    - name: Test
#      run: bash test.sh

      
